export const subjects = [
    "Painting",
    "Sculpture",
    "Photography",
    "Architecture",
    "Literature",
    "Poetry",
    "Calligraphy",
    "Theater",
    "Music Composition",
    "Film Studies",
    "Art History",
    "Graphic Design",
    "Animation",
    "Philosophy",
    "Mythology",
    "Linguistics",
    "Anthropology",
    "Cultural Studies",
    "Creative Writing",
    "Archaeology",
    "Astronomy",
    "Physics",
    "Chemistry",
    "Biology",
    "Ecology",
    "Geology",
    "Meteorology",
    "Oceanography",
    "Paleontology",
    "Quantum Mechanics",
    "Neuroscience",
    "Botany",
    "Zoology",
    "Astrobiology",
    "Evolutionary Biology",
    "Artificial Intelligence",
    "Data Science",
    "Machine Learning",
    "Software Engineering",
    "Game Development",
    "Cybersecurity",
    "Blockchain",
    "Quantum Computing",
    "Robotics",
    "Human-Computer Interaction",
    "Mathematics",
    "Statistics",
    "Topology",
    "Cryptography",
    "Number Theory",
    "Economics",
    "Finance",
    "Investing",
    "Entrepreneurship",
    "Marketing",
    "Behavioral Economics",
    "Urban Planning",
    "Sustainability",
    "Renewable Energy",
    "Environmental Science",
    "Agriculture",
    "Horticulture",
    "Aquaculture",
    "Forestry",
    "Food Science",
    "Culinary Arts",
    "Nutrition",
    "Medicine",
    "Surgery",
    "Veterinary Science",
    "Pharmacology",
    "Public Health",
    "Genetics",
    "Biotechnology",
    "Psychology",
    "Cognitive Science",
    "Sociology",
    "Political Science",
    "Law",
    "International Relations",
    "History",
    "Religious Studies",
    "Education",
    "Pedagogy",
    "Special Education",
    "STEM Education",
    "Liberal Arts",
    "Yoga",
    "Martial Arts",
    "Sports Science",
    "Astronautics",
    "Aerospace Engineering",
    "Automotive Design",
    "Mechanical Engineering",
    "Civil Engineering",
    "Electrical Engineering",
    "Materials Science",
    "Nanotechnology",
    "Textile Engineering",
    "Industrial Design",
    "Fashion Design",
    "Interior Design",
    "Game Theory",
    "Ethics",
    "Epistemology",
    "Existentialism",
    "Astrophysics",
    "Cosmology",
    "String Theory",
    "Memetics",
    "Folklore",
    "Cartography",
    "Landscape Architecture",
    "Sound Design",
    "Cinematography",
    "Virtual Reality",
    "Augmented Reality",
    "Cryptozoology",
    "Mycology",
    "Ichthyology",
    "Ornithology",
    "Herpetology",
    "Entomology",
    "Forensic Science",
    "Criminology",
    "Liberal Studies",
    "Music Production",
    "Sound Engineering",
    "Set Design",
    "Choreography",
    "Acoustics",
    "Ceramics",
    "Metalworking",
    "Woodworking",
    "Leathercraft",
    "Glassblowing",
    "3D Printing",
    "Wearable Technology",
    "Social Media Analysis",
    "UX/UI Design",
    "Ecosystem Modeling",
    "Geopolitics",
    "Military Strategy",
    "Ocean Exploration",
    "Space Exploration",
    "Climate Science",
    "Hydrology",
    "Cave Science",
    "Speleology",
    "Volcanology",
    "Seismology",
    "Planetary Science",
    "Bioinformatics",
    "Ethnobotany",
    "Permaculture",
    "Biophysics",
    "Aerodynamics",
    "Avionics",
    "Biomimetics",
    "Origami",
    "Typography",
    "Horology",
    "Gemology",
    "Horsemanship",
    "Parkour",
    "Freediving",
    "Surfing",
    "Gliding",
    "Drone Racing",
    "Model Making",
    "Model Rocketry",
    "Kite Design",
    "Board Game Design",
    "Puzzle Design",
    "Algorithmic Art",
    "Generative Design",
    "Installation Art",
    "Performance Art",
    "Street Art",
    "Tattoo Art",
    "Astrological Studies",
    "Tarot Reading",
    "Runology",
    "Numismatics",
    "Philately",
    "Heraldry",
    "Genealogy",
    "Futurology",
    "Speculative Design",
    "Conservation Biology",
    "Wildlife Management",
    "Paleoclimatology",
    "Bioethics",
    "Art Therapy",
    "Music Therapy",
    "Dance Therapy",
    "Drama Therapy",
    "Mindfulness Studies",
    "Spiritual Practices",
    "Alchemy",
    "Shamanism",
    "Cryptid Hunting",
    "Mythical Beasts Studies"
];